### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by simon-p-r** [CascadeEnergy/aws-promised#1]
Hi

I would like to contribute, what other modules do you need integrating?  I am currently learning  bluebird so think this will help me to learn.

Thanks
Simon

**Comment by nackjicholson** [comment]
@simon-p-r Thanks a lot!

People love:
- [EC2](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/EC2.html)
- [S3](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html)

Right now I only have that one example with [getIam()](https://github.com/nackjicholson/aws-promised/blob/master/lib/getIam.js) and it's [test](https://github.com/nackjicholson/aws-promised/blob/master/test/lib/getIam.js)

You're welcome to implement any clients you want though! I may have some feedback for you when you put in a pull request. I'll try not too be too anal, but I'll speak up on things that will help keep the code / comments / and tests consistent across modules. Please see [style guide](https://github.com/CascadeEnergy/node-style-guide)

I don't really know of a way to test that the clients actually work as intended after the `.promisifyAll`. Might need to do some integration or e2e tests at some point. For now though...just write some code that uses the promisified client and see if it works :)

Let me know if I can help you with any questions.

**Comment by simon-p-r** [comment]
Ok thanks I have used EC2 and a little bit of S3 so will start with EC2,  I will try some pull requests and  I will appreciate any feedback (anal is totally acceptable) as very new to coding.  What framework do you use for building your servers?  I would try maybe to write tests that create base machine to start with.  I wish I could figure out how to create an custom AMI image from scratch with core stack built on to it.

**Comment by nackjicholson** [comment]
Hold off on doing this to this repo. I just released this repo last night, and wasn't expecting immediate community response :) Happy to have it though! I talked with my team this morning, and we want to manage this project internally at CascadeEnergy, so I'll be forking it to a CascadeEnergy repo and that will be the new home for this.

Cheers! Sorry about the confusion.

**Comment by nackjicholson** [comment]
Do work to there https://github.com/CascadeEnergy/aws-promised

**Comment by simon-p-r** [comment]
OK what does memoize do?

**Comment by nackjicholson** [comment]
https://lodash.com/docs#memoize

It essentially makes it so that if you call the factory method `getIam` with the same set of options twice. You will get the same object back instead of making two of them.

It's just a way of not making a new client every time the method is called.

By the way I added [s3](https://github.com/CascadeEnergy/aws-promised/blob/master/lib/getS3.js), and an [example usage file](https://github.com/CascadeEnergy/aws-promised/blob/master/examples/s3.js). It ended up being an exact copy paste job and change of variable names.

Not sure that's a good thing...probably an abstraction we could do. But I don't really care right now :wink:
